import os
import sys
import argparse
import subprocess
import time
from github import Github, Auth
from langchain_openai import ChatOpenAI  # <-- ИЗМЕНЕНИЕ
from langchain_core.messages import HumanMessage, SystemMessage
from dotenv import load_dotenv

load_dotenv()

REPO_NAME = os.getenv("GITHUB_REPOSITORY")
GITHUB_TOKEN = os.getenv("GH_PAT") or os.getenv("GITHUB_TOKEN")
# Берем ключ OpenRouter
API_KEY = os.getenv("OPENROUTER_API_KEY") 

def setup_git_user():
    subprocess.run(["git", "config", "--global", "user.name", "AI Agent"], check=True)
    subprocess.run(["git", "config", "--global", "user.email", "agent@ai.com"], check=True)

def get_file_structure():
    files_list = []
    for root, dirs, files in os.walk("."):
        # Исключаем лишнее
        for ignore in [".git", ".github", "venv", "__pycache__", ".idea", ".vscode"]:
            if ignore in dirs: dirs.remove(ignore)
        
        for file in files:
            if file.endswith((".py", ".md", ".txt", ".yml", ".yaml", ".json", ".sh")):
                path = os.path.join(root, file)
                files_list.append(path)
    return "\n".join(files_list)

def parse_llm_response(response_text):
    import re
    files = []
    # DeepSeek может много "думать" (теги <think>), нам нужен только код в тегах <FILE>
    pattern = re.compile(r'<FILE path="(.*?)">\n(.*?)\n</FILE>', re.DOTALL)
    matches = pattern.findall(response_text)
    for path, content in matches:
        files.append({"path": path, "content": content})
    return files

def main(issue_number):
    if not API_KEY:
        print("Error: OPENROUTER_API_KEY is missing")
        sys.exit(1)

    print(f"--- Processing Issue #{issue_number} ---")
    
    auth = Auth.Token(GITHUB_TOKEN)
    g = Github(auth=auth)
    repo = g.get_repo(REPO_NAME)
    issue = repo.get_issue(number=int(issue_number))
    
    print(f"Task: {issue.title}")
    
    # Настройка OpenRouter
    llm = ChatOpenAI(
        model="tngtech/deepseek-r1t2-chimera:free",
        openai_api_key=API_KEY,
        base_url="https://openrouter.ai/api/v1", # <-- base_url
        temperature=0.1
    )

    files_context = get_file_structure()
    
    system_prompt = """Ты - опытный Python-разработчик. 
    Твоя задача - написать код для решения Issue.
    
    ФОРМАТ ОТВЕТА (Строго соблюдай!):
    <FILE path="имя_файла.py">
    код файла целиком
    </FILE>
    
    Верни ВЕСЬ файл целиком.
    НЕ используй Markdown блоки (```python). Только теги <FILE>."""
    
    user_prompt = f"""
    ЗАДАЧА: {issue.title}
    ОПИСАНИЕ: {issue.body}
    
    ФАЙЛЫ В ПРОЕКТЕ:
    {files_context}
    """

    print("Asking OpenRouter (DeepSeek)...")
    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=user_prompt)
    ]
    
    # DeepSeek обычно не падает по Rate Limit так часто, как Gemini Free, 
    # но простой try/except оставим
    try:
        response = llm.invoke(messages)
    except Exception as e:
        print(f"LLM Error: {e}")
        sys.exit(1)
    
    generated_files = parse_llm_response(response.content)
    
    if not generated_files:
        print("No files generated. Raw response:")
        print(response.content)
        sys.exit(1)

    setup_git_user()
    branch_name = f"feature/issue-{issue_number}"
    
    try:
        subprocess.run(["git", "checkout", "-b", branch_name], check=True)
    except subprocess.CalledProcessError:
        subprocess.run(["git", "checkout", branch_name], check=True)

    for file_data in generated_files:
        path = file_data["path"]
        content = file_data["content"]
        os.makedirs(os.path.dirname(path) if os.path.dirname(path) else ".", exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Updated: {path}")

    try:
        subprocess.run(["git", "add", "."], check=True)
        status = subprocess.run(["git", "status", "--porcelain"], capture_output=True, text=True)
        if status.stdout.strip():
            subprocess.run(["git", "commit", "-m", f"Fix: {issue.title}"], check=True)
            subprocess.run(["git", "push", "origin", branch_name], check=True)
            
            # Создание PR
            try:
                pr = repo.create_pull(
                    title=f"Resolve: {issue.title}",
                    body=f"Generated by DeepSeek Agent.\nFixes #{issue_number}",
                    head=branch_name,
                    base="main"
                )
                print(f"PR Created: {pr.html_url}")
            except Exception as e:
                print(f"PR creation failed (maybe exists?): {e}")
        else:
            print("No changes to commit.")
    except Exception as e:
        print(f"Git error: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--issue", required=True, help="Issue number")
    args = parser.parse_args()
    main(args.issue)