import argparse
import os
import re
import sys
from configs.config import Config
from configs.llm import invoke_llm, PROMPTS
from configs.git_tools import setup_git, get_repo, checkout_branch, commit_and_push, get_project_files

def parse_files(text):
    pattern = re.compile(r'<FILE path="([^"\n]+)">\n(.*?)\n</FILE>', re.DOTALL)
    files = []
    for match in pattern.finditer(text):
        files.append({"path": match.group(1), "content": match.group(2)})
    return files

def check_iteration_limit(pr_number):
    """Считает количество циклов исправлений"""
    try:
        repo = get_repo()
        pr = repo.get_pull(int(pr_number))
        comments = list(pr.get_issue_comments())
        
        bot_reviews = 0
        for comment in comments:
            # Считаем комментарии с нашим маркером
            if "⚠️ **Review Status:**" in comment.body or "⚠️ Найдены замечания" in comment.body:
                bot_reviews += 1
        
        print(f"🔄 Текущая итерация исправлений: {bot_reviews}/5")
        
        if bot_reviews >= 5:
            msg = "⛔ Превышен лимит итераций (5). Требуется вмешательство человека."
            pr.create_issue_comment(msg)
            print("❌ Limit reached. Exiting.")
            sys.exit(0) # Выходим без ошибки CI, просто останавливаем работу
            
    except Exception as e:
        print(f"Warning: Could not check iteration limit: {e}")

def run_coder():
    parser = argparse.ArgumentParser()
    parser.add_argument("--issue", help="Issue number")
    parser.add_argument("--pr", help="PR number (fix mode)")
    parser.add_argument("--fix", action="store_true")
    args = parser.parse_args()

    Config.validate()
    setup_git()
    repo = get_repo()

    # --- РЕЖИМ 1: New Feature ---
    if args.issue and not args.fix:
        issue = repo.get_issue(int(args.issue))
        print(f"🚀 Задача: {issue.title}")
        branch_name = f"feature/issue-{args.issue}"
        checkout_branch(branch_name, create_new=True)
        
        system_prompt = PROMPTS["coder_new"]
        user_prompt = f"TITLE: {issue.title}\nBODY: {issue.body}"
        
        # Для новой задачи PR создается в конце, issue здесь
        pr_obj = None 

    # --- РЕЖИМ 2: Fix (Loop) ---
    elif args.pr and args.fix:
        print(f"🔧 Исправление PR #{args.pr}")
        check_iteration_limit(args.pr) # <-- Проверка лимита
        
        pr_obj = repo.get_pull(int(args.pr))
        branch_name = pr_obj.head.ref
        checkout_branch(branch_name)
        
        # Получаем последний комментарий с замечаниями
        comments = list(pr_obj.get_issue_comments())
        last_feedback = comments[-1].body if comments else "General fix required."
        
        current_code = get_project_files()
        system_prompt = PROMPTS["coder_fix"]
        user_prompt = f"CODE:\n{current_code}\n\nFEEDBACK:\n{last_feedback}"
    
    else:
        print("Неверные аргументы")
        return

    # --- ГЕНЕРАЦИЯ И ЗАПИСЬ ---
    print("🤖 Генерация кода...")
    response = invoke_llm(system_prompt, user_prompt)
    files = parse_files(response)

    if not files:
        print("⚠️ Код не сгенерирован")
        return

    for f in files:
        path = f["path"]
        if path in ["coder.py", "reviewer.py", "configs/llm.py"]: continue # Защита
        
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            with open(path, "w", encoding="utf-8") as file:
                file.write(f["content"])
            print(f"📝 Записан: {path}")
        except Exception as e:
            print(f"❌ Ошибка записи {path}: {e}")

    # --- ПУШ ---
    msg = "AI Fixes based on review" if args.fix else f"AI Feature: {issue.title}"
    if commit_and_push(branch_name, msg):
        print("✅ Изменения отправлены")
        
        # Создаем PR только если это была новая задача (не фикс)
        if args.issue and not args.fix:
            try:
                pr = repo.create_pull(
                    title=f"Resolve: {issue.title}",
                    body="Generated by AI Code Agent",
                    head=branch_name,
                    base="main"
                )
                print(f"🔗 PR создан: {pr.html_url}")
            except Exception as e:
                print(f"Info: {e}")

if __name__ == "__main__":
    run_coder()